### ISSUE TITLE
User experience testing of CLI

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp-cli#212]
DoD:
Go through each command in the CLI and try out each option. create issues for all issues encountered.
login
logout
download
post-search
get-file
head-file
get-bundle
get-bundles-checkout
post-bundles-checkout
put-subscription
get-subscription
get-subscriptions
delete-subscription
delete-bundle
put-bundle
upload
put-file

**Comment by justincc** [comment]
HI @kozbo. What is this linked to?

**Comment by jnkrupp** [comment]
@justincc I think he meant to assign this to me and assigned it to you by mistake

**Comment by justincc** [comment]
Thanks @jnkrupp

**Comment by amarjandu** [comment]
Tested Working:
post-search
get-file
head-file
get-bundle
get-bundles-checkout
post-bundles-checkout

Bugs Found:
Login
Logout
download --bundle-uuid --replica aws : Error AUTH required


Awaiting Triage: 
put-subscription
get-subscription
get-subscriptions
delete-subscription
delete-bundle
put-bundle
upload
put-file

Notes: 
Need to fix login issues in order to be able to with required auth. 
Need callback URL to test subscriptions

**Comment by amarjandu** [comment]
Created ticket #219 to start talking about help menu improvements.
