### ISSUE TITLE
Make `--layout=bundle` the default

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/dcp-cli#425]
Originally brought up by @ESapenaVentura (on Slack, `#data-store`):

> I tried hca dss download-manifest  this morning with a modified manifest (deleted almost all lines because I just wanted to test how it function), and it downloaded the files to the temporary hidden folder and, in the end, it modified the manifest to indicate the hidden folders where the files (with modified names) are. I tried downloading by bundle id and the behaviour is completely different, downloads the bundle at a non-hidden directory with the original name of the file. Is the first behaviour intended?

**Comment by ESapenaVentura** [comment]
Hi! Just as a clarification, I do prefer bundle over the `default` layout simply because you actually get the files on visible folders, with their original names.

This is how I see it from a scientific user perspective:

`I want to download the data from this experiment because, for what I see in the portal, it fits with the data that I have generated/the study I would like to conduct. I would like to download the fastq files in order to be able to analyse them in R along with my data. In order to be able to do this, I will need some kind of metadata that links the files and the files itself.`

For this purpose, I'd suggest a default layout that will download just the fastq files and not all the Json/pdfs associated within the bundle, leaving those files all together inside a visible folder that is named after the `project uuid` or any other unique name. If any programmatic user is interested in the bundles, they will research about how to get them, probably querying the dss API or changing the layout.

For the scientist/bioinformatic who wants to analyse the data/compare it to their own datasets, they are probably interested in getting the metadata .tsv available in the browser, and then the fastq files by using our tool.

I'm sure that this is not an easy thing to implement, but I am under the impression that this is what the user would want. Any thoughts about this, @gabsie?

**Comment by hannes-ucsc** [comment]
@jessebrennan convinced me that we need more input from the UX folks before we make a decision. Yes, there is inconsistency between `download` and `download-manifest` but then again we don't expect normal users to use `download` because we've been told that they don't understand bundles. 

@ESapenaVentura, you first paragraph makes it clear: you prefer `--layout` to default to `bundle`. The part below that confuses me slightly, it sound as if you are proposing more sweeping changes. If that is the case, I would suggest filing a new ticket and documenting precisely how you think the program should behave.

Handing this ticket over to UX for more input.

**Comment by ESapenaVentura** [comment]
Thanks @hannes-ucsc! I'll write a ticket as soon as I can :) I want to hear UX's side of it before as well, in case I'm missing something

**Comment by gabsie** [comment]
Hey, @ESapenaVentura and @hannes-ucsc and @jessebrennan - So I would suggest Enrique files all this in his usability notes test document. (He has one as a tester)
I suppose we will also get other people's feedback from the usability test, external ones as well (currently 15 people).
It's good to incorporate and analyse all feedback before we jump to actually implementing this.
Thanks everyone, and Enrique for the thoughts!
Gabby

**Comment by hannes-ucsc** [comment]
@natanlao I assume this was an error.  2f86015 seems to be completely unrelated. I think you may want fix the ticket reference in your commit and force-push to develop as soon as possible to avoid disrupting other developers.

**Comment by natanlao** [comment]
This was a mistake on my part, I meant to close #435. Sorry about that.

**Comment by theathorn** [comment]
@gabsie Do you have an ETA for the completion of the UX feedback?

**Comment by theathorn** [comment]
Would users prefer #237?

**Comment by theathorn** [comment]
Closing in favor of #237 and #474.
